# Generated by Django 3.1.2 on 2020-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201103_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
