# Generated by Django 3.1.2 on 2020-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201104_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='service',
            field=models.CharField(blank=True, choices=[('p', 'Pédiatrie'), ('g', 'Médecine général'), ('ne', 'Neurologie'), ('d', 'Pneumlogie')], max_length=2, null=True),
        ),
    ]
